services:
  comfyui:
    devices:
      - "nvidia.com/gpu=all"      # Podman CDI hook hands over the NVIDIA GPU
    security_opt:
      - label=disable             # Needed on SELinux hosts (ignored elsewhere)
