version: "3.9"

services:
  comfyui:
    image: comfyui:latest
    container_name: comfyui
    build:
      context: .
      dockerfile: dockerfile
    user: "1000:1000"
    expose:
      - "8188"
    volumes:
      - ./custom_nodes:/workspace/custom_nodes
      - ./models:/workspace/models
      - ./output:/workspace/output
      # persist all your settings & extra nodes
      - ./settings:/app/ComfyUI/user/default:rw
      # persist just your saved flows (overrides the workflows/ in default)
      - ./flows:/app/ComfyUI/user/default/workflows:rw
      # Caches persistent
      - ./cache:/workspace/.cache
      - ./nv:/root/.nv
    tmpfs:
      - /workspace/input:size=1G,mode=1777
      - /tmp:size=8G,mode=1777
    environment:
      # Caches
      - XDG_CACHE_HOME=/workspace/.cache
      - HF_HOME=/workspace/.cache/huggingface
      - TRANSFORMERS_CACHE=/workspace/.cache/huggingface/transformers
      - HUGGINGFACE_HUB_CACHE=/workspace/.cache/huggingface/hub
      - TORCH_HOME=/workspace/.cache/torch
      - PIP_CACHE_DIR=/workspace/.cache/pip
    deploy:
      resources:
        limits:
          memory: 40g          # hard limit
          cpus: "8.0"
        reservations:
          memory: 35g           # OOM-Killer earlier
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu           # Docker alternative to runtime: nvidia + NVIDIA_VISIBLE_DEVICES
    restart: "no"

  proxy:
    image: nginx:alpine
    container_name: comfyui-proxy
    depends_on:
      - comfyui
    ports:
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,Z
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro,Z
      - ./nginx/certs:/etc/nginx/certs:ro,Z
