services:
  comfyui:
    image: comfyui:latest
    container_name: comfyui
    build:
      context: .
      dockerfile: dockerfile
    user: "1000:1000"
    expose:
      - "8188"
    mem_limit: "40g"
    cpus: "8.0"
    volumes:
      - ./custom_nodes:/workspace/custom_nodes
      - ./models:/workspace/models
      - ./output:/workspace/output
      # Persist all user settings and extra nodes
      - ./settings:/app/ComfyUI/user/default:rw
      # Persist only saved workflows (overrides the default workflows/ folder)
      - ./flows:/app/ComfyUI/user/default/workflows:rw
      # Keep caches on disk for reproducibility and to save RAM
      - ./cache:/workspace/.cache
    tmpfs:
      - /workspace/input:size=1G,mode=1777
      - /tmp:size=8G,mode=1777
    shm_size: "2g"  # Help ffmpeg/OpenCV with large jobs
    environment:
      # Cache directories on the persistent volume
      - XDG_CACHE_HOME=/workspace/.cache
      - HF_HOME=/workspace/.cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/workspace/.cache/huggingface/hub
      - TRANSFORMERS_CACHE=/workspace/.cache/huggingface/transformers
      - TORCH_HOME=/workspace/.cache/torch
      - PIP_CACHE_DIR=/workspace/.cache/pip
    device_requests:
      - driver: nvidia
        count: 1
        capabilities: [gpu]
    restart: "no"

  proxy:
    image: nginx:alpine
    container_name: comfyui-proxy
    depends_on:
      - comfyui
    ports:
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,Z
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro,Z
      - ./nginx/certs:/etc/nginx/certs:ro,Z
