x-host-paths: &host-paths
  custom_nodes: &host-custom_nodes
    source: ./custom_nodes
    read_only: false
  models: &host-models
    source: ./models
  output: &host-output
    source: ./output
    read_only: false
  settings: &host-settings
    source: ./settings
    read_only: false
  flows: &host-flows
    source: ./flows
    read_only: false
  cache: &host-cache
    source: ./cache
    read_only: false

x-comfyui-resources: &comfyui-resources
  mem_limit: "40g"
  cpus: "8.0"
  tmpfs:
    - /tmp:size=8G,mode=1777

services:
  volume-permissions:
    image: alpine:3.20
    container_name: comfyui-volume-permissions
    command: >-
      sh -c '
        set -eu
        for dir in custom_nodes models output settings flows cache; do
          target="/mnt/$${dir}"
          if ! install -d -m 0777 "$${target}"; then
            echo "install failed for $${target}, attempting fallback" >&2
            mkdir -p "$${target}"
            chmod 0777 "$${target}"
          fi
          chown -R 1000:1000 "$${target}"
        done
      '
    volumes:
      - type: bind
        <<: *host-custom_nodes
        target: /mnt/custom_nodes
      - type: bind
        <<: *host-models
        target: /mnt/models
      - type: bind
        <<: *host-output
        target: /mnt/output
      - type: bind
        <<: *host-settings
        target: /mnt/settings
      - type: bind
        <<: *host-flows
        target: /mnt/flows
      - type: bind
        <<: *host-cache
        target: /mnt/cache
    restart: "no"

  comfyui:
    image: comfyui:latest
    container_name: comfyui
    <<: *comfyui-resources
    build:
      context: .
      dockerfile: dockerfile
    user: "1000:1000"
    expose:
      - "8188"
    depends_on:
      volume-permissions:
        condition: service_completed_successfully
    volumes:
      - type: bind
        <<: *host-custom_nodes
        target: /workspace/ComfyUI/custom_nodes
      - type: bind
        <<: *host-models
        target: /workspace/ComfyUI/models
      - type: bind
        <<: *host-output
        target: /workspace/ComfyUI/output
      # Persist all user settings and extra nodes
      - type: bind
        <<: *host-settings
        target: /workspace/ComfyUI/user/default
      # Persist only saved workflows (overrides the default workflows/ folder)
      - type: bind
        <<: *host-flows
        target: /workspace/ComfyUI/user/default/workflows
      # Keep caches on disk for reproducibility and to save RAM
      - type: bind
        <<: *host-cache
        target: /workspace/.cache
    shm_size: "2g"  # Help ffmpeg/OpenCV with large jobs
    environment:
      # Cache directories on the persistent volume
      - XDG_CACHE_HOME=/workspace/.cache
      - HF_HOME=/workspace/.cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/workspace/.cache/huggingface/hub
      - TRANSFORMERS_CACHE=/workspace/.cache/huggingface/transformers
      - TORCH_HOME=/workspace/.cache/torch
      - PIP_CACHE_DIR=/workspace/.cache/pip
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: "no"

  proxy:
    image: nginx:alpine
    container_name: comfyui-proxy
    depends_on:
      - comfyui
    ports:
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,Z
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro,Z
      - ./nginx/certs:/etc/nginx/certs:ro,Z
